-- SQL Migration: 008_saved_reports.sql
-- Description: Create saved_reports table for Custom Report Builder templates.

CREATE TABLE IF NOT EXISTS public.saved_reports (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    config JSONB NOT NULL,
    created_by UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    schedule TEXT CHECK (schedule IN ('none', 'daily', 'weekly', 'monthly')) DEFAULT 'none',
    schedule_recipients TEXT[] DEFAULT '{}'::text[],
    last_run_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Architectural Comment on JSONB for Config:
-- Using JSONB for `config` allows the report builder wizard to store arbitrary data sources, 
-- selected column arrays, dynamic filter expressions (field, operator, value), and sort directions 
-- without requiring complex relational schema tables or ALTER TABLE migrations.

COMMENT ON TABLE public.saved_reports IS 'Saved custom report configurations generated by the 4-step Report Builder wizard.';
COMMENT ON COLUMN public.saved_reports.config IS 'JSONB object containing source table, selected columns, filter conditions, and sort orders.';

-- Enable Row Level Security (RLS)
ALTER TABLE public.saved_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own saved reports"
ON public.saved_reports
FOR SELECT
TO authenticated
USING (auth.uid() = created_by);

CREATE POLICY "Users can insert their own saved reports"
ON public.saved_reports
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = created_by);

CREATE POLICY "Users can update their own saved reports"
ON public.saved_reports
FOR UPDATE
TO authenticated
USING (auth.uid() = created_by);

CREATE POLICY "Users can delete their own saved reports"
ON public.saved_reports
FOR DELETE
TO authenticated
USING (auth.uid() = created_by);
