-- SQL Migration: 009_saved_reports.sql
-- Description: Create saved_reports table for Custom Report Builder templates.

CREATE TABLE IF NOT EXISTS public.saved_reports (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    config JSONB NOT NULL,
    created_by UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    schedule TEXT CHECK (schedule IN ('none', 'daily', 'weekly', 'monthly')) DEFAULT 'none',
    schedule_recipients TEXT[] DEFAULT '{}'::text[],
    last_run_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

COMMENT ON TABLE public.saved_reports IS 'Saved custom report configurations generated by the 4-step Report Builder wizard.';

-- Enable Row Level Security (RLS)
ALTER TABLE public.saved_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own saved reports"
ON public.saved_reports
FOR SELECT
TO authenticated
USING (auth.uid() = created_by);

CREATE POLICY "Users can insert their own saved reports"
ON public.saved_reports
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = created_by);

CREATE POLICY "Users can update their own saved reports"
ON public.saved_reports
FOR UPDATE
TO authenticated
USING (auth.uid() = created_by);

CREATE POLICY "Users can delete their own saved reports"
ON public.saved_reports
FOR DELETE
TO authenticated
USING (auth.uid() = created_by);
